version: '3.8'
services:
  db:
    container_name: db
    hostname: db
    image: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=snippets
    volumes:
      - ~/Dev/postgres:/var/lib/postgresql/data/