version: '3.8'
services:
  db:
    container_name: db
    hostname: db
    image: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=snippets
    volumes:
      - ~/Dev/postgres:/var/lib/postgresql/data/
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - db
    container_name: keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "9990:8080"
    restart: unless-stopped
    networks:
      - local-keycloak

networks:
  local-keycloak: