spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true
      path: /h2
      show-sql: true
  datasource:
    url: jdbc:h2:file:~/Dev/h2/snippets
    username: sa
    password:
    driverClassName: org.h2.Driver
server:
  port: 1337