spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/snippets
          jwk-set-uri: http://localhost:8083/auth/realms/snippets/protocol/openid-connect/certs
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/snippets
    username: postgres
    password: secret
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
server:
  port: 1337
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    operations-sorter: method
    path: /swagger-ui.html


