spring:
  kafka:
    bootstrap-servers:
      - ${HOST:localhost}:29092
    template:
      default-topic: snippets
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://${HOST:localhost}:${DB_PORT:5432}/snippets
    username: postgres
    password: secret
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
server:
  port: 1337
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    operations-sorter: method
    path: /swagger-ui.html

jwt:
  secret: secret
  jwtExp: 300000000


